# Generated by Django 4.2.19 on 2025-03-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
    ]
